/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN.
 *
 * More info on www.robotran.be
 *
 * Universite catholique de Louvain, Belgium
 *
 * Last update : Tue May 19 13:31:40 2015
 * --------------------------------------------------------
 *
 */
#include "user_model.h"
#include "mbs_binder_public.h"
#include "mbs_loader.h"
#include "useful_functions.h"
// ============================================================ //


UserModel* mbs_new_user_model()
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));

    return um;
}

void mbs_delete_user_model(UserModel* um)
{
    free(um);
}

 void mbs_load_user_model(MbsInfos* mbs_infos, UserModel* um)
{

}

void mbs_bind_user_model(MbsInfos* mbs_infos, UserModel* um)
{

}

void mbs_print_user_model(UserModel* um)
{

}

void mbs_get_user_model_size(int *n_user_model)
{
    *n_user_model  = 0;
}

void mbs_get_user_model_list(int *user_model_list)
{
    user_model_list[0] = 0;
}

void mbs_save_um(FILE* stream, UserModel* um)
{

}
// ============================================================ //

